spring:
 profiles:
  active:
   -dev

-----------
spring:
 profiles: dev
 application:
  name: microservicecloud-config-dev

-----------------
spirng:
 profiles: test
 application:
  name: microservicecloud-config-test